#!/bin/bash

# # # #
# Simple script to change desktop backgrounds in gnome to 
# set a random image in a given folder.
# # # #

DEBUG=0

function help {
	echo "Usage: `basename $0` [-hr] path"
}

function debug {
	if [ $DEBUG -ne 0 ]; then
		echo $@
	fi
}
numPhotos=0
#Parse options
while getopts "hr:" OPTION; do
	case $OPTION in
		h)
			help
			exit 0
			;;
		r)
			if [ -z $OPTARG ]; then
				echo "No path specified. Exiting."
				exit 1
			fi
			photos=`find $OPTARG -type f`
			numPhotos=`echo $photos | wc -w`
			;;
	esac
done

#If the user did not choose to pick recursively
if [ $numPhotos -eq 0 ]; then
	if [ -z $1 ]; then
		echo "No path specified. Exiting."
		exit 1
	fi
	photos=`ls -1 $1`
	numPhotos=`echo $photos | wc -w`
	# Keep track of the base for the file path later on.
	# We do not run into this problem with find.
	base="$1/"
fi

randID=`randN $numPhotos`

# Iterate over the photos to pick the photo to use next.
count=0
for photo in `echo $photos`; do
	if [ $count == $randID ]; then
		break
	fi
	count=$(($count + 1))
done

debug $photo

# Set the background
gsettings set org.gnome.desktop.background picture-uri "file://$base$photo"
